### ISSUE TITLE
test/map: panic when SSA-built

### ISSUE THREAD

**Issue by binarycrusader** [4ad/go#23]
test/map.go currently panics when SSA-built and then executed on a sparc64 system.

It is cross-compiled and cross-linked for sparc64 from an amd64 system using:

```bash
SSATEST=1 GOSSAHASH="" GOOS=solaris GOARCH=sparc64 go tool compile map.go
GOOS=solaris GOARCH=sparc64 go tool link map.o
```

When executed it fails as follows:
```
$ ./map
panic: len(mfi) = 1


goroutine 1 [running]:
panic(0x13e0c0, 0xc42000d1c0)
        /builds/srwalker/golang/go-sparc/src/runtime/panic.go:507 +0x5f8
main.testbasic()
        /builds/srwalker/golang/go-sparc/test/map.go:111 +0xbd2c
main.main()
        /builds/srwalker/golang/go-sparc/test/map.go:33 +0x34
```

**Comment by binarycrusader** [comment]
A minimal test case reduced from the original test/map.go seems to indicate some sort of code generation issue for loops:

```go
package main

const count = 2 

//go:noinline
func fillmfi(mfi map[float32]int) {
        for i := 0; i < count; i++ {
                mfi[float32(i)] = 10 * i
        }   
}

func main() {
        mfi := make(map[float32]int)
        fillmfi(mfi)
        if len(mfi) != count {
                println("len(mfi) =", len(mfi))
                panic(1)
        }   
}
```

Unrolling the loop manually allows the reduced test case to work as expected.

**Comment by binarycrusader** [comment]
The problem here is somehow related to the code emitted for the FXTOS/FXTOD by the logic for that in sparc64/ssa.go for the `mfi[float32(i)]`, not sure exactly what yet:

```asm
0x11048: stx       %g1, [%sp + 0x7f7]
0x1104c: ld        [%sp + 0x7f7], %f0
0x11050: fxtos     %d0, %f0
```

**Comment by jrtc27** [comment]
That should be a `ldd       [%sp + 0x7f7], %f0` to load a double, no? You just stored a 64-bit "integer" and the next instruction is a double-to-float conversion.

EDIT: Ok, it should still be that, but I got forgot what `fxtos` did; it's actually the 64-bit int to float conversion.

**Comment by binarycrusader** [comment]
The problem is compounded by how we do some magical register rewrites for fp registers and the subtleties of FXTOS which makes this a little mysterious.

In particular, behind the scenes I'm doing this:
```go
                p = gc.Prog(v.Op.Asm())
                p.From.Type = obj.TYPE_REG
                p.From.Reg = r
                p.To.Type = obj.TYPE_REG
                p.To.Reg = r
```

...but the semi-magical register rewrites is turning that into %d0 and %f0 respectively.

FXTOS is supposed to be *64-bit integer* to *single-precision* floating-point number, but you're correct that the notation used in the sparc architecture manual implies that the *source* register must be a %d* register, I had noticed that but had (unwisely) dismissed it.

This also explains why the logic for the rewrites (which I was getting ready to go find) was turning the first argument into %d0.

**Comment by jrtc27** [comment]
You're doing a 64-bit store and should be generating a 64-bit load, so I don't understand how that gets turned into a 32-bit load?

**Comment by binarycrusader** [comment]
Because I was doing a loadByType:

```go
                p := gc.Prog(storeByType(ft))
                p.From.Type = obj.TYPE_REG
                p.From.Reg = r1
                p.To.Type = obj.TYPE_MEM
                p.To.Reg = sparc64.REG_RSP
                p.To.Offset = -8 + sparc64.StackBias
                p = gc.Prog(loadByType(tt))
                p.From.Type = obj.TYPE_MEM
                p.From.Reg = sparc64.REG_RSP
                p.From.Offset = -8 + sparc64.StackBias
                p.To.Type = obj.TYPE_REG
                p.To.Reg = r
                p = gc.Prog(v.Op.Asm())
                p.From.Type = obj.TYPE_REG
                p.From.Reg = r
                p.To.Type = obj.TYPE_REG
                p.To.Reg = r
```

**Comment by binarycrusader** [comment]
Fixed FXTOS by always loading the integer as a double.  (Thanks @jrtc27)

**Comment by jrtc27** [comment]
Could there be similar issues with `FITOD` trying to load 64 bits? Also going the other way with `FDTOI` and `FSTOX`?

**Comment by binarycrusader** [comment]
I believe so; I was already looking around for other cases, and that looks like another one.  Fascinatingly enough though, none of the tests in test/* catch that.  All of the integer and floating conversion tests pass now.
